FROM python:3.10-slim

WORKDIR /app

# Instala as dependências necessárias para o Streamlit e BigQuery
RUN pip install --no-cache-dir \
    streamlit>=1.32.0 \
    plotly>=5.20.0 \
    google-cloud-bigquery>=3.17.0 \
    pandas>=2.2.0 \
    pyarrow>=15.0.0 \
    db-dtypes>=1.2.0

COPY app.py /app/app.py

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]
